### ISSUE TITLE
hdfull error enumerar recursos de peliculas

### ISSUE THREAD

**Issue by advidsec** [alfa-addon/addon#1197]
Al intentar ver los diferentes recursos para ver una pelicula, da el siguiente error, cosa que no pasa con los capitulos de las series donde seleccionas el capitulo y ves donde puedes verlo sin problema:

2022-11-13 19:35:22.403 T:1488974016   ERROR: ######## ERROR #########
2022-11-13 19:35:22.403 T:1488974016   ERROR:     [alfa.platformcode.launcher.run] Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/platformcode/launcher.py", line 264, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/channels/hdfull.py", line 1073, in findvideos
                                                it1.append(Item(channel=item.channel, action="set_status__", title=title, url=url_targets,
                                            UnboundLocalError: local variable 'title' referenced before assignment
2022-11-13 19:35:31.065 T:1477677248   ERROR: GetDirectory - Error getting plugin://plugin.video.alfa/?ewogICAgImFjdGlvbiI6ICJmaW5kdmlkZW9zIiwgCiAgICAiY2hhbm5lbCI6ICJoZGZ1bGwiLCAKICAgICJmYW5hcnQiOiAiaHR0cHM6Ly9pbWFnZS50bWRiLm9yZy90L3Avb3JpZ2luYWwvcW4xVUJjRzlHME13eUV4VlJBTnJSMHBBR093LmpwZyIsIAogICAgImluZm9MYWJlbHMiOiB7CiAgICAgICAgImZhbmFydCI6ICJodHRwczovL2ltYWdlLnRtZGIub3JnL3QvcC9vcmlnaW5hbC9xbjFVQmNHOUcwTXd5RXhWUkFOclIwcEFHT3cuanBnIiwgCiAgICAgICAgImdlbnJlIjogIkF2ZW50dXJhLCBGYW1pbGlhLCBDaWVuY2lhIGZpY2NpXHUwMGYzbiIsIAogICAgICAgICJtZWRpYXR5cGUiOiAibW92aWUiLCAKICAgICAgICAib3JpZ2luYWxfbGFuZ3VhZ2UiOiAibmwiLCAKICAgICAgICAib3JpZ2luYWx0aXRsZSI6ICJDYXB0YWluIE5vdmEiLCAKICAgICAgICAicGxvdCI6ICJVbmEgcGlsb3RvIGRlIGNvbWJhdGUgdmlhamEgZW4gZWwgdGllbXBvIHBhcmEgc2FsdmFyIGFsIG11bmRvIGRlIHVuIGZ1dHVybyBkZXNhc3RyZSBhbWJpZW50YWwuIFBlcm8gZGViaWRvIGEgdW4gZWZlY3RvIHNlY3VuZGFyaW8sIHNlIGFjYWJhIHZvbHZpZW5kbyBqb3ZlbiBkZSBudWV2byB5IG5hZGllIGxhIHRvbWFyXHUwMGUxIGVuIHNlcmlvLiIsIAogICAgICAgICJwb3B1bGFyaXR5IjogOS40NjEsIAogICAgICAgICJyYXRpbmciOiA2LjEsIAogICAgICAgICJyZWxlYXNlX2RhdGUiOiAiMDEvMTIvMjAyMSIsIAogICAgICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9pbWFnZS50bWRiLm9yZy90L3Avb3JpZ2luYWwvcHJJTlJlU2JDa29rdGNSYnJJZ21iWTRmMHRwLmpwZyIsIAogICAgICAgICJ0aXRsZSI6ICJDYXB0YWluIE5vdmEiLCAKICAgICAgICAidG1kYl9pZCI6ICI4ODE5NTciLCAKICAgICAgICAidm90ZXMiOiA1NywgCiAgICAgICAgInllYXIiOiAyMDIxCiAgICB9LCAKICAgICJ0ZXh0X2JvbGQiOiB0cnVlLCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9pbWFnZS50bWRiLm9yZy90L3Avb3JpZ2luYWwvcHJJTlJlU2JDa29rdGNSYnJJZ21iWTRmMHRwLmpwZyIsIAogICAgInRpdGxlIjogIkNhcHRhaW4gTm92YSBbQ09MT1IgYmx1ZV0oUGVuZGllbnRlKVsvQ09MT1JdIiwgCiAgICAidXJsIjogImh0dHBzOi8vaGRmdWxsLmRpZ2l0YWwvcGVsaWN1bGEvY2FwdGFpbi1ub3ZhIyMjMjg2NzY7MiIKfQ%3d%3d
2022-11-13 19:35:31.068 T:1900454848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.alfa/?ewogICAgImFjdGlvbiI6ICJmaW5kdmlkZW9zIiwgCiAgICAiY2hhbm5lbCI6ICJoZGZ1bGwiLCAKICAgICJmYW5hcnQiOiAiaHR0cHM6Ly9pbWFnZS50bWRiLm9yZy90L3Avb3JpZ2luYWwvcW4xVUJjRzlHME13eUV4VlJBTnJSMHBBR093LmpwZyIsIAogICAgImluZm9MYWJlbHMiOiB7CiAgICAgICAgImZhbmFydCI6ICJodHRwczovL2ltYWdlLnRtZGIub3JnL3QvcC9vcmlnaW5hbC9xbjFVQmNHOUcwTXd5RXhWUkFOclIwcEFHT3cuanBnIiwgCiAgICAgICAgImdlbnJlIjogIkF2ZW50dXJhLCBGYW1pbGlhLCBDaWVuY2lhIGZpY2NpXHUwMGYzbiIsIAogICAgICAgICJtZWRpYXR5cGUiOiAibW92aWUiLCAKICAgICAgICAib3JpZ2luYWxfbGFuZ3VhZ2UiOiAibmwiLCAKICAgICAgICAib3JpZ2luYWx0aXRsZSI6ICJDYXB0YWluIE5vdmEiLCAKICAgICAgICAicGxvdCI6ICJVbmEgcGlsb3RvIGRlIGNvbWJhdGUgdmlhamEgZW4gZWwgdGllbXBvIHBhcmEgc2FsdmFyIGFsIG11bmRvIGRlIHVuIGZ1dHVybyBkZXNhc3RyZSBhbWJpZW50YWwuIFBlcm8gZGViaWRvIGEgdW4gZWZlY3RvIHNlY3VuZGFyaW8sIHNlIGFjYWJhIHZvbHZpZW5kbyBqb3ZlbiBkZSBudWV2byB5IG5hZGllIGxhIHRvbWFyXHUwMGUxIGVuIHNlcmlvLiIsIAogICAgICAgICJwb3B1bGFyaXR5IjogOS40NjEsIAogICAgICAgICJyYXRpbmciOiA2LjEsIAogICAgICAgICJyZWxlYXNlX2RhdGUiOiAiMDEvMTIvMjAyMSIsIAogICAgICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9pbWFnZS50bWRiLm9yZy90L3Avb3JpZ2luYWwvcHJJTlJlU2JDa29rdGNSYnJJZ21iWTRmMHRwLmpwZyIsIAogICAgICAgICJ0aXRsZSI6ICJDYXB0YWluIE5vdmEiLCAKICAgICAgICAidG1kYl9pZCI6ICI4ODE5NTciLCAKICAgICAgICAidm90ZXMiOiA1NywgCiAgICAgICAgInllYXIiOiAyMDIxCiAgICB9LCAKICAgICJ0ZXh0X2JvbGQiOiB0cnVlLCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9pbWFnZS50bWRiLm9yZy90L3Avb3JpZ2luYWwvcHJJTlJlU2JDa29rdGNSYnJJZ21iWTRmMHRwLmpwZyIsIAogICAgInRpdGxlIjogIkNhcHRhaW4gTm92YSBbQ09MT1IgYmx1ZV0oUGVuZGllbnRlKVsvQ09MT1JdIiwgCiAgICAidXJsIjogImh0dHBzOi8vaGRmdWxsLmRpZ2l0YWwvcGVsaWN1bGEvY2FwdGFpbi1ub3ZhIyMjMjg2NzY7MiIKfQ%3d%3d) failed

**Comment by advidsec** [comment]
pd: solo pasa con peliculas "pendientes" de ver

**Comment by lopezvg** [comment]
Arreglado.  Reinicia Kodi y prueba de nuevo.

Para el futuro te sugiero que reportes los problema en el foro: https://alfa-addon.com/link-forums/pasos-para-un-correcto-reporte-de-error.24/
