### ISSUE TITLE
Alfa crashes when initializing - SyntaxError in `downloads.py` module

### ISSUE THREAD

**Issue by ProtossGP32** [alfa-addon/addon#1362]
### ¿Verificaste que el error es de Alfa?

- [X] Verifiqué que el error solo es de Alfa

### Enlace al reporte de error

https://github.com/user-attachments/files/17968292/kodi.log

### Sistema operativo

Raspberry Pi 3B+

### Versión de Alfa

3.10.2 - Fix 4

### Versión de Kodi

Kodi 18

### Descripción del problema

**HARDWARE:** Raspberry Pi 3B+
**KODI VERSION:**  18.7
**ALFA ADD-ON VERSION:** 3.10.2 - FIX4
**PYTHON VERSION:** 

```bash
pi@retropie:~/.kodi/temp $ python --version
Python 2.7.16
pi@retropie:~/.kodi/temp $ python3 --version
Python 3.7.3
```

**ISSUE:** Alfa fails to initialize, can't access the main menu.

**LOGS:** 
[kodi.log](https://github.com/user-attachments/files/17968292/kodi.log)

When looking at the log errors, we find a syntax error in `downloads.py` file:

```logs
2024-12-01 09:31:44.509 T:1385148608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: invalid syntax (downloads.py, line 2054)
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/videolibrary_service.py", line 572, in <module>
                                                check_for_update(overwrite=False)
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/videolibrary_service.py", line 392, in check_for_update
                                                from modules import downloads
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/modules/downloads.py", line 2054
                                                )
                                                ^
                                            SyntaxError: invalid syntax
                                            -->End of Python script error report<--
```

Looking at the code, I see trailing commas after the last method's parameters, causing the SyntaxError:

```python
        # Si se activó el ajuste "Mover archivo descargado a videoteca", movemos el archivo
        if config.get_setting("downloads_library_move") is True:
            # Asignamos una ruta a la carpeta de pelis o series en videoteca según contentType
            if item.contentType == "movie":
                item_library_path = filetools.join(
                    config.get_videolibrary_path(),
                    config.get_setting("folder_movies"),
                    *filetools.split(item.downloadFilename), # --> Bad trailing comma
                )
            elif item.contentType == "episode":
                item_library_path = filetools.join(
                    config.get_videolibrary_path(),
                    config.get_setting("folder_tvshows"),
                    *filetools.split(item.downloadFilename), # --> Bad trailing comma
                )
```
The source code doesn't contain this comma, so I suspect it's something related to some compilation steps?

**WORKAROUND:** Remove the trailing commas from the last parameters.

**Comment by SistemaRayoXP** [comment]
Restart Kodi, wait for a couple of minutes and try again. It should be working with the latest fix.

**Comment by ProtossGP32** [comment]
Alfa updated to 3.10.2 - Fix 5, the error didn't appear again. Thanks!

Closing the issue.
