### ISSUE TITLE
SeriesBlanco roto (o más bien CloudFlare)

### ISSUE THREAD

**Issue by t1254362** [alfa-addon/addon#239]
Hola,
Me he encontrado con que SeriesBlanco, si bien puede navegar por la web (listar series, buscar, últimos capítulos, mostrar enlaces), una vez le das a un enlace cualquiera se queda "cargando" y al final da error (mirar logs).

Entrando desde la biblioteca me sale el siguiente log, que muestra una recursividad ¿infinita? (obviamente no, porque acaba) en downloadPage:

```
22:02:43.351 T:1511781360   ERROR: ######## ERROR #########
22:02:43.352 T:1511781360   ERROR:     [alfa.platformcode.launcher.run] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/platformcode/launcher.py", line 150, in run
                                                itemlist = channel.play(item)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/channels/videolibrary.py", line 432, in play
                                                itemlist = getattr(channel, "play")(item)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/channels/seriesblanco.py", line 337, in play
                                                data = httptools.downloadpage(item.url).data
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 247, in downloadpage
                                                cookies=cookies, replace_headers=replace_headers, add_referer=add_referer)
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 243, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/osmc/.kodi/addons/plugin.video.alfa/core/httptools.py", line 118, in downloadpage
                                                request_headers = dict(headers)
                                            SystemExit
22:02:53.861 T:1511781360 WARNING: Invalid media type "list"
22:02:54.633 T:1511781360 WARNING: Previous line repeats 2 times.
```

Pero si vamos vía addon y con log debug, entonces si es infinita (hasta que yo le doy atrás): https://pastebin.com/sA112tPP
- Download, cloudflare detectado (espeando 4 segundo), autorizando.. autorización OK. download, cloudflare detectado....

¿Se ha jodido el anticloudflare?

**Comment by t1254362** [comment]
Diría que hoy ya no pasa. Tal vez fue algo temporal.

**Comment by Intel11** [comment]
Hola @t1254362  el problema es generalizado de cloudflare no solo de seriesblanco, puedes comprobarlo en gnula.nu por ejemplo.

Encontramos este script que si funciona pero usa nodejs y estamos viendo la posibilidad de adaptarlo a Alfa:

https://github.com/Anorov/cloudflare-scrape/blob/master/cfscrape/__init__.py

Estamos mirando pero mas ojos ven mejor ;)

Saludos.

**Comment by t1254362** [comment]
Justo venía a comentar que se había vuelto a joder (anoche funcionó un rato, supongo que se desactivó el cloudflare o algo).

Veo que usa Node.js simplemente como intérprete de JavaScript. Por mi bien, tengo por ahí un node.js
Recuerdo, aunque no lo encuentro ahora, que había una librería que era un wrapper hacía los motores JS, así el cliente podía tener diferentes y la librería escogía uno (mientras escribía esto lo he encontrado, pone que ya no está mantenido: https://github.com/doloopwhile/PyExecJS)

Y buscando ahora "javascript python interpreter" he encontrado esto (sale en los primeros resultados) que no se que tal será: https://github.com/amol-/dukpy y otro https://github.com/polydojo/jispy

Recuerdo haber visto esa librería hace unos años, cuando aun usaba Js2Py (en el historial se ve cuando lo quitaron) y por aquel entonces era bastante "standalone" (gracias a que js2py era también otra librería python).

Le volveré a dar un vistazo, era realmente sencilla de usar, el problema será la integración, aunque veo que lo que se retorna es un hashmap propio en el que se añaden las cosas (headers, status, etc.)

**Comment by Intel11** [comment]
Hola, en https://nodejs.org

Está para descargar nodejs

Estamos tratando de adecuar ese script a Alfa.

La desventaja es que los users tienen que descargar el nodejs, estamos probando en windows y linux, faltaría tambien android.

**Comment by Intel11** [comment]
Hola @t1254362 tenemos este cloudflare.py funcionando para ponerlo en la carpeta core, pero necesita el nodejs instalado para que funcione, probado en linux y windows, falta probar en android.

Pero sería excelente que funcione sin el node.js :)

Saludos.
[cloudflare.zip](https://github.com/alfa-addon/addon/files/1886531/cloudflare.zip)

**Comment by t1254362** [comment]
Ya lo he puesto y parece que va bien. Tal vez lo que yo habría intentado habría sido hacer un wrapper hacia el código original (a no ser que sea complicado), porque como lo vuelvan a cambiar habrá que volver a editar el archivo este vs bajar el código del otro repo y listo (aunque supongo que mirando el diff del repo se verá donde ha tocado y se puede cambiar fácilmente, también es cierto que no parece que tenga muchos commits, no es un OpenLoad 😆 )
