### ISSUE TITLE
Error al tratar de actualizar la videoteca

### ISSUE THREAD

**Issue by brainstormi** [alfa-addon/addon#262]
Cuando trato de actualizar la videoteca de series desde el addon de Alfa, la actualización se termina siempre en el mismo punto, antes de terminar de procesar todas las series. En kodi.log aparece el siguiente error:
20:17:08.104 T:140396326205184   ERROR: ######## ERROR #########
20:17:08.104 T:140396326205184   ERROR:     [alfa.videolibrary_service.check_for_update] Se ha producido un error al actualizar las series
20:17:08.104 T:140396326205184   ERROR: ######## ERROR #########
20:17:08.104 T:140396326205184   ERROR:     [alfa.videolibrary_service.check_for_update] An exception of type AttributeError occured. Arguments:
                                            ("'NoneType' object has no attribute 'contentSerieName'",)

**Comment by susobaco** [comment]
Puede que sea este error también?

2019-02-20 20:12:18.279 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.279 T:140317235861248   ERROR:     [alfa.core.jsontools.load] **NO** se ha podido cargar el JSON
2019-02-20 20:12:18.279 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.279 T:140317235861248   ERROR:     [alfa.core.jsontools.load] Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.alfa/core/jsontools.py", line 38, in load
                                                value = json.loads(*args, **kwargs)
                                              File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
2019-02-20 20:12:18.284 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.284 T:140317235861248   ERROR:     [alfa.core.jsontools.load] **NO** se ha podido cargar el JSON
2019-02-20 20:12:18.284 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.284 T:140317235861248   ERROR:     [alfa.core.jsontools.load] Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.alfa/core/jsontools.py", line 38, in load
                                                value = json.loads(*args, **kwargs)
                                              File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
2019-02-20 20:12:18.285 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.285 T:140317235861248   ERROR:     [alfa.channels.videolibrary.verify_playcount_series] ** No tiene PlayCount
2019-02-20 20:12:18.286 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.286 T:140317235861248   ERROR:     [alfa.channels.videolibrary.verify_playcount_series] ** Estado de actualización: True / PlayCount: {'': 0, '1x06': 0, '1x05': 0, '1x04': 0, '1x03': 0, '1x02': 0, '1x01': 0, '1x09': 0, '1x08': 0, '1x07': 0, '1x10': 0, 'season 1': 0, '1x11': 0}
2019-02-20 20:12:18.287 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.287 T:140317235861248   ERROR:     [alfa.check_for_update] Se ha producido un error al actualizar las series
2019-02-20 20:12:18.287 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.287 T:140317235861248   ERROR:     [alfa.check_for_update] An exception of type ValueError occured. Arguments:
                                            ("invalid literal for int() with base 10: ''",)
2019-02-20 20:12:18.384 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.384 T:140317235861248   ERROR:     [alfa.core.jsontools.load] **NO** se ha podido cargar el JSON
2019-02-20 20:12:18.384 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.384 T:140317235861248   ERROR:     [alfa.core.jsontools.load] Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.alfa/core/jsontools.py", line 38, in load
                                                value = json.loads(*args, **kwargs)
                                              File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
2019-02-20 20:12:18.388 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.388 T:140317235861248   ERROR:     [alfa.platformcode.xbmc_videolibrary.mark_content_as_watched_on_alfa] Error en la SQL: select strFileName, playCount from movie_view where (strPath like "/home/kodi/Librería/Movies/The Beyond (2017)/The Beyond (2017).nfo" or strPath like "/home/kodi/Librería/Movies/The Beyond (2017)/The Beyond (2017).nfo"): 0 registros
2019-02-20 20:12:18.388 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.388 T:140317235861248   ERROR:     [alfa.core.jsontools.load] **NO** se ha podido cargar el JSON
2019-02-20 20:12:18.388 T:140317235861248   ERROR: ######## ERROR #########
2019-02-20 20:12:18.388 T:140317235861248   ERROR:     [alfa.core.jsontools.load] Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.alfa/core/jsontools.py", line 38, in load
                                                value = json.loads(*args, **kwargs)
                                              File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
2019-02-20 20:12:18.393 T:140317235861248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'str' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.alfa/videolibrary_service.py", line 333, in <module>
                                                check_for_update(overwrite=False)
                                              File "/home/kodi/.kodi/addons/plugin.video.alfa/videolibrary_service.py", line 260, in check_for_update
                                                videolibrary.list_movies(item_dummy, silent=True)
                                              File "/home/kodi/.kodi/addons/plugin.video.alfa/channels/videolibrary.py", line 123, in list_movies
                                                visto = new_item.library_playcounts.get(os.path.splitext(f)[0], 0)
                                            AttributeError: 'str' object has no attribute 'get'
                                            -->End of Python script error report<--
