### ISSUE TITLE
El modo mediaserver en Firefox nunca termina de cargar

### ISSUE THREAD

**Issue by juancroldan** [alfa-addon/addon#765]
Al intentar usar Alfa en modo mediaserver, se queda colgado con el mensaje "Estableciendo conexión...".

Durante la carga el programa muestra un par de warnings de deprecación y este error:

```Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "<string>", line 318, in get_proxy_list_monitor
  File "<string>", line 397, in randomize_lists
AttributeError: 'module' object has no attribute 'log_enable'
```

Al modificar el XML de configuración para habilitar el modo debug, ya no aparece ese error, aunque el log es un poco más completo. Adjunto los logs de alfa al usar el modo debug y al no usarlo.

* Navegador utilizado: Firefox 72.0.1
* Versión de Alfa: 2.9.5
* Versión de Python: 2.7.13
* Versión del sistema: Raspbian GNU/Linux 9 (stretch), recién instalado
* [alfa-debug.log](https://github.com/alfa-addon/addon/files/4098605/alfa-debug.log)
* [alfa.log](https://github.com/alfa-addon/addon/files/4098604/alfa.log)

Estoy suscrito a la issue, cualquier info que os haga falta para solucionar el error os la paso rápidamente.

**Comment by juancroldan** [comment]
Al acceder desed Chrome, carga sin problema.
