### ISSUE TITLE
AnimeFLV no medio funciona.

### ISSUE THREAD

**Issue by askotx** [alfa-addon/addon#781]
Desde el día 07/03/2020 ha dejado de funcionar el canal de animeflv
Kodi: 17.4
Version: 3.0.5 & 3.0.2
OS: Retropie (Linux Debian Raspberry)

Curosiamente tengo otra Raspberry Pi, con Libreelec con Kodi 17.6 y version del addon 3.0.2 y si me permite ver los videos, descargarlos, etc.

`20:25:07.457 T:1347060656   ERROR: ######## ERROR #########
20:25:07.457 T:1347060656   ERROR:     [alfa.platformcode.launcher.run] Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/platformcode/launcher.py", line 257, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/channels/animeflv.py", line 147, in novedades_episodios
                                                data = get_source(item.url, patron=patr)
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/channels/animeflv.py", line 68, in get_source
                                                data = httptools.downloadpage(url).data
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/core/httptools.py", line 485, in downloadpage
                                                session = cloudscraper.create_scraper()                             #El dominio necesita CloudScraper
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/lib/cloudscraper/__init__.py", line 541, in create_scraper
                                                scraper = cls(**kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/lib/cloudscraper/__init__.py", line 134, in __init__
                                                cipherSuite=self.cipherSuite
                                              File "/home/pi/.kodi/addons/plugin.video.alfa/lib/cloudscraper/__init__.py", line 76, in __init__
                                                self.ssl_context.set_alpn_protocols(['http/1.1'])`

**Comment by askotx** [comment]
Ya funciona, pero al parecer si tengo 2 dispositivos con kodi en una misma red local con este addon solo funcionará  uno de ellos, algo de sesión con cloudflare o algo asi lei del codigo un poco.
