### ISSUE TITLE
Problema al cargar lista de servidores de jkanime

### ISSUE THREAD

**Issue by askotx** [alfa-addon/addon#886]
El canal no tiene problemas para mostrar los resultados de: Ultimos episodios, Ultimos animes, Buscar, etc. El problema radica al seleccionar un episodio 'n' o el mas reciente, el log arroja este error:

```
2020-10-26 20:27:55.257 T:1391457152   ERROR: ######## ERROR #########
2020-10-26 20:27:55.257 T:1391457152   ERROR:     [alfa.platformcode.launcher.run] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.alfa/platformcode/launcher.py", line 235, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "/storage/.kodi/addons/plugin.video.alfa/channels/jkanime.py", line 190, in findvideos
                                                url = decode_url(data)
                                              File "/storage/.kodi/addons/plugin.video.alfa/channels/jkanime.py", line 228, in decode_url
                                                part0 = part[1].split("String['fromCharCode'")[0]
                                            IndexError: list index out of range
2020-10-26 20:28:15.219 T:1375798144   ERROR: GetDirectory - Error getting plugin://plugin.video.alfa/?
```

**Comment by shlibidon** [comment]
Hola, reinicia Kodi para que se aplique el "parche".
Por ahora verás que no sale uno de los links "directos", cuando haya tiempo se intentará arreglar.

Gracias por el aviso, puedes también usar el foro para reportar errores y muchas mas cosas:
https://alfa-addon.com/

Saludos,

**Comment by askotx** [comment]
Lo que hayan ajustado hizo el truco, gracias.
